import React from 'react';
import Layout from '../components/Layout';
import SlideShow from '../components/SlideShow';
import Nav from '../components/Nav';

var settings = {
    images: [
      { url: require('../assets/images/bg01.jpg'), position: 'center' },
      { url: require('../assets/images/bg02.jpg'), position: 'center' },
      { url: require('../assets/images/bg03.jpg'), position: 'center' },
    ],
    // Delay.
    delay: 6000,
  };

const ArtGallery= () => (
<>
    <Layout>
    <Nav />
        <h1>ART GALLERY AT ETHEREUM PORTLAND</h1>
        <p>CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT CHECK IT OUT </p>
        <SlideShow settings={settings} />
    </Layout>
</>
);

export default ArtGallery;
